### ISSUE TITLE
ToDo before publication

### ISSUE THREAD

**Issue by duerrsimon** [bioicons/pdb2vector#13]
- [ ] add SSDraw (https://github.com/ncbi/SSDraw) 
- [ ] make retrieval of structure more robust and allow alphafold structures
- [ ] add preview image of the svg in the output
- [ ] add different profiles for cartoon/sphere/spacefill
- [ ] add option to get just the outline of the protein similar to these illustrations: ![image](https://github.com/bioicons/pdb2vector/assets/16979577/387ffdf4-7d53-42e6-b8f1-8948f2e4fb44) Could potentially also do:
  - get cutout and color scan, merge them. Sort the colors by lightness and cluster them to give a bit more texture
  - if different colors are selected one could voxelize each color separately and keep the dimensions intact (not sure how this looks like at the interface).
  - The 2d surfaces look nice if "inner glow is applied" to give them a bit more texture.

**Comment by duerrsimon** [comment]
Add functions to set illustrative or stylized styles using this code 
Reference see here: https://github.com/molstar/molstar/blob/6edbae80db340134341631f669eec86543a0f1a8/src/mol-plugin-ui/structure/quick-styles.tsx#L84C11-L84C19

`viewerInstance.plugin.canvas3d.setProps({
                postprocessing: {
                    outline: {
                        name: 'on',
                        params: {
                            scale: 1,
                            color: {r:0,b:0, g:0},
                            threshold: 0.25,
                            includeTransparent: true,
                        }
                    },
                    occlusion: {
                        name: 'on',
                        params: {
                            multiScale: { name: 'off', params: {} },
                            radius: 5,
                            bias: 0.8,
                            blurKernelSize: 15,
                            samples: 32,
                            resolutionScale: 1,
                            color: {r:0,b:0, g:0},
                        }
                    },
                    shadow: { name: 'off', params: {} },
                }
            });`
